source("D:/Program Files/R/R-4.4.1/sandbox/fontalign/R/utils.R")
source("D:/Program Files/R/R-4.4.1/sandbox/fontalign/R/backend-route.R")
source("D:/Program Files/R/R-4.4.1/sandbox/fontalign/R/device-detect.R")
source("D:/Program Files/R/R-4.4.1/sandbox/fontalign/R/dpi-align.R")
source("D:/Program Files/R/R-4.4.1/sandbox/fontalign/R/check-system.R")
library(ggplot2)
library(cli)

cat("=== fontalign_check_system() ===\n")
out <- fontalign_check_system()
print(out)

cat("\n=== device detection ===\n")
cairo_pdf_path <- tempfile(fileext = ".pdf")
grDevices::cairo_pdf(cairo_pdf_path, width = 5, height = 4)
cat("vector? ", device_is_vector(), "\n")
cat("current: ", device_current(), "\n")
cat("native dpi (vector): ", device_native_dpi(), "\n")
grDevices::dev.off()
